# Generated by Django 5.0 on 2023-12-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_image',
            field=models.URLField(default='https://images4.alphacoders.com/132/1325361.png', max_length=2000),
        ),
    ]
